org: syedahmed
app: aws-python-http-api-project
service: aws-python-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, 'dev'}
  environment:
    VAR_NAME: ${self:custom.variables.${self:provider.stage}.VAR_NAME}

custom:
  variables:
    dev:
      VAR_NAME: devValue
    prod:
      VAR_NAME: prodValue

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
